# Makefile for rleClock

OBJS = rleClock.o font.o

default: install

install: rleClock
	mv rleClock ../rleClock.out

rleClock: $(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) $(OBJS) -o rleClock $(LIBS) -lm

font.c:font.src makeFont
	chmod +x makeFont
	makeFont font.src > font.c

lint:
	lint -I$(RI) rleClock.c

# Clean up installed stuff and binaries
pristine: clean
# installed version removed from parent dir

clean:	clean-pgm

# Dependencies.
rleClock.o font.o:$(RI)/rle_config.h
