Utah Raster Toolkit: cnv/pgmtorle.c File Reference
pgmtorle.c File Reference
#include <stdio.h>
#include <pgm.h>
#include "rle.h"
Macros
#define NO_DECLARE_MALLOC
#define VPRINTF if (verbose || header) fprintf
Typedefs
typedef unsigned char U_CHAR
Functions
void read_pgm_header ()
void write_rle_header ()
void write_rle_data ()
int main (int argc, char **argv)
Variables
static char rcsid [] = "$Header: /l/spencer/src/urt/cnv/RCS/pgmtorle.c,v 3.0.1.5 1992/04/30 13:57:29 spencer Exp $"
FILE * fp
int format
int width
int height
int verbose = 0
int header = 0
int do_alpha = 0
gray maxval
rle_hdr hdr
Macro Definition Documentation
#define NO_DECLARE_MALLOC
Definition at line 40 of file pgmtorle.c.
#define VPRINTF if (verbose || header) fprintf
Definition at line 43 of file pgmtorle.c.
Typedef Documentation
typedef unsigned char U_CHAR
Definition at line 45 of file pgmtorle.c.
Function Documentation
int main (int argc, char ** argv)
Definition at line 138 of file pgmtorle.c.
 {
    int      oflag = 0;
    char     *periodP, *pgmname = 0, *outname = 0;
    static char  filename[BUFSIZ];
 /*
  * Get those options.
  */
    if (!scanargs(argc,argv,
        "% v%- h%- a%- o%-outfile!s infile.pgm%s\n(\
 \tConvert a PGM file to URT RLE format.\n\
 \t-a\tFake an alpha channel.  Alpha=0 when input=0, 255 otherwise.\n\
 \t-h\tPrint header of PGM file.\n\
 \t-v\tVerbose mode.\n\
 \tInput file name is forced to end in .pgm.)",
        &verbose,
        &header,
        &do_alpha,
        &oflag, &outname,
        &pgmname))
       exit(-1);
    hdr = *rle_hdr_init( (rle_hdr *)NULL );
    rle_names( &hdr, cmd_name( argv ), outname, 0 );
 /*
  * Open the file.
  */
    if (pgmname == NULL) {
       strcpy(filename, "stdin");
       fp = stdin;
       }
    else {
       periodP = strrchr(pgmname, '.');
       strcpy(filename, pgmname);
       if (periodP) {
          if (strcmp(periodP, ".pgm")) /* does not end in pgm */
             strcat(filename, ".pgm");
          }
       else              /* no ext -- add one */
          strcat(filename, ".pgm");
       if (!(fp = fopen(filename, "r"))) {
          fprintf(stderr, "%s: Cannot open %s for reading.\n",
          hdr.cmd, filename);
          exit(-1);
          }
       }
 /*
  * Read the PGM file header.
  */
    read_pgm_header();
    if (header)
       exit(0);
 /*
  * Write the rle file header.
  */
    hdr.rle_file = rle_open_f( cmd_name( argv ), outname, "w" );
    rle_addhist(argv, (rle_hdr *)NULL, &hdr);
    write_rle_header();
 /*
  * Write the rle file data.
  */
    write_rle_data();
    fclose(fp);
    return 0;
 }
void read_pgm_header ()
Definition at line 59 of file pgmtorle.c.
References do_alpha, height, and width.
 {
    pgm_readpgminit(fp, &width, &height, &maxval, &format);
    VPRINTF(stderr, "Image type: 8 bit grayscale\n");
    VPRINTF(stderr, "Full image: %dx%d\n", width, height);
    VPRINTF(stderr, "Maxval:     %d\n", maxval);
    if (do_alpha)
       VPRINTF(stderr, "Computing alpha channel...\n");
 }
void write_rle_data ()
Definition at line 89 of file pgmtorle.c.
References rle_hdr::cmd, hdr, height, rle_puteof(), rle_putrow(), rle_row_alloc(), rle_row_free(), and width.
 {
     register int        x;
     register int        scan;
     register gray   *grayrow, *gP;
     rle_pixel   ***scanlines, **scanline;
     /*
      * Allocate some memory.
      */
     grayrow = pgm_allocrow(width);
     scanlines = (rle_pixel ***)malloc( height * sizeof(rle_pixel **) );
     RLE_CHECK_ALLOC( hdr.cmd, scanlines, "scanline pointers" );
     for ( scan = 0; scan < height; scan++ )
     RLE_CHECK_ALLOC( hdr.cmd, (rle_row_alloc(&hdr, &scanlines[scan]) >= 0),
              "pixel memory" );
     /*
      * Loop through the pgm files image window, write blank lines outside
      * active window.
      */
     for (scan = 0; scan < height; scan++) {
     pgm_readpgmrow(fp, grayrow, width, maxval, format);
     scanline = scanlines[height - scan - 1];
         for (x = 0, gP = grayrow; x < width; x++, gP++) {
         scanline[RLE_RED][x] = *gP;
         if (do_alpha)
         scanline[RLE_ALPHA][x] = (*gP ? 255 : 0);
     }
     }
     /*
      * Write out data in URT order (bottom to top).
      */
     for ( scan = 0; scan < height; scan++ )
     {
     rle_putrow(scanlines[scan], width, &hdr);
     rle_row_free( &hdr, scanlines[scan] );
     }
     free( scanlines );
     VPRINTF(stderr, "Done -- write eof to RLE data.\n");
     rle_puteof(&hdr);
     /*
      * Free up some stuff.
      */
 }
void write_rle_header ()
Definition at line 71 of file pgmtorle.c.
References rle_hdr::alpha, rle_hdr::background, do_alpha, hdr, height, rle_hdr::ncolors, rle_put_setup(), width, rle_hdr::xmax, rle_hdr::xmin, rle_hdr::ymax, and rle_hdr::ymin.
 {
    hdr.xmin    = 0;
    hdr.xmax    = width-1;
    hdr.ymin    = 0;
    hdr.ymax    = height-1;
    hdr.ncolors = 1;
    hdr.background = 0;
    RLE_SET_BIT(hdr, RLE_RED);
    if (do_alpha) {
       hdr.alpha = 1;
       RLE_SET_BIT(hdr, RLE_ALPHA);
       }
    rle_put_setup(&hdr);
 }
Variable Documentation
int do_alpha = 0
Definition at line 52 of file pgmtorle.c.
int format
Definition at line 50 of file pgmtorle.c.
FILE* fp
Definition at line 49 of file pgmtorle.c.
rle_hdr hdr
Definition at line 54 of file pgmtorle.c.
int header = 0
Definition at line 52 of file pgmtorle.c.
int height
Definition at line 51 of file pgmtorle.c.
gray maxval
Definition at line 53 of file pgmtorle.c.
char rcsid[] = "$Header: /l/spencer/src/urt/cnv/RCS/pgmtorle.c,v 3.0.1.5 1992/04/30 13:57:29 spencer Exp $" static
Definition at line 29 of file pgmtorle.c.
int verbose = 0
Definition at line 52 of file pgmtorle.c.
int width
Definition at line 51 of file pgmtorle.c.