Utah Raster Toolkit: lib/rle_getcom.c File Reference
rle_getcom.c File Reference
#include <stdio.h>
#include "rle.h"
Functions
static char * match (char *n, char *v)
char * rle_getcom (char *name, rle_hdr *the_hdr) const
Function Documentation
static char* match (char * n, char * v) static
Definition at line 50 of file rle_getcom.c.
 {
     for ( ; *n != '\0' && *n != '=' && *n == *v; n++, v++ )
     ;
     if (*n == '\0' || *n == '=') {
     if ( *v == '\0' )
         return v;
     else if ( *v == '=' )
         return ++v;
     }
     return NULL;
 }
char* rle_getcom (char * name, rle_hdr * the_hdr) const
Definition at line 81 of file rle_getcom.c.
Referenced by display_rle(), find_most_used(), and load_x_map().
 {
     CONST_DECL char ** cp;
     char * v;
     if ( the_hdr->comments == NULL )
     return NULL;
     for ( cp = the_hdr->comments; *cp; cp++ )
     if ( (v = match( name, *cp )) != NULL )
         return v;
     return NULL;
 }