Utah Raster Toolkit: get/getami/show3.c File Reference
show3.c File Reference
#include <stdio.h>
#include <string.h>
#include <exec/types.h>
#include <graphics/gfxbase.h>
#include <intuition/intuition.h>
#include <iff.h>
Functions
struct Library * OpenLibrary ()
struct Screen * OpenScreen ()
void CenterScreen (register struct Screen *, int *, int *)
void Fail (char *text, int status)
main (int argc, char *argv[])
Variables
struct Library * IntuitionBase = ((void *)0)
struct Library * IFFBase = ((void *)0)
struct GfxBase * GfxBase = ((void *)0)
struct NewScreen ns
struct Screen * screen [3] = { ((void *)0) , ((void *)0) , ((void *)0) }
APTR ifffile = ((void *)0)
char * fname [3] = { ((void *)0) , ((void *)0) , ((void *)0) }
int fsiz = 0
Function Documentation
void CenterScreen (register struct Screen * , int * , int *)
Definition at line 12 of file CenterScreen.c.
 {
   int c640, c320, r400, r200, w, h, max_x, max_y;
   struct Preferences prefs;
   extern struct GfxBase *GfxBase;
   GetPrefs(&prefs, sizeof(prefs));
   c640 = 640 + prefs.ColumnSizeChange;
   c320 = c640 / 2;
   r200 = 200 + prefs.RowSizeChange;
   r400 = r200 * 2;
   max_y = (GfxBase->DisplayFlags & PAL) ? MAX_Y_PAL : MAX_Y_NTSC;
   if (screen->ViewPort.Modes & LACE){
     max_y *= 2;
   }
   max_x = MAX_X;
   if (screen->ViewPort.Modes & HIRES){
     max_x *= 2;
   }
   if (screen->ViewPort.DWidth <= max_x) {
     w = screen->ViewPort.DWidth;
   }else{
     w = max_x;
   }
   if (screen->ViewPort.DHeight <= max_y) {
     h = screen->ViewPort.DHeight;
   }else{
     h = max_y;
   }
   if (screen->ViewPort.Modes & HIRES){
     screen->ViewPort.DxOffset += (c640 - w) / 2;
     *dx = screen->ViewPort.DxOffset / 2;
   }else{
       screen->ViewPort.DxOffset += (c320 - w) / 2;
       *dx = screen->ViewPort.DxOffset;
   }
   if (screen->ViewPort.Modes & LACE){
     screen->ViewPort.DyOffset += (r400 - h) / 2;
     *dy = screen->ViewPort.DyOffset / 2;
   }else{
     screen->ViewPort.DyOffset += (r200 - h) / 2;
     *dy = screen->ViewPort.DyOffset;
   }
   RemakeDisplay();
 }
void Fail (char * text, int status)
Definition at line 36 of file show3.c.
References fname, fsiz, IFFBase, IntuitionBase, and screen.
 {
     int i;
     if(ifffile) CloseIFF(ifffile);
     if(screen[0]) CloseScreen(screen[0]);
     if(screen[1]) CloseScreen(screen[1]);
     if(screen[2]) CloseScreen(screen[2]);
     if (fsiz) {
       for (i=0; i<3; i++) {
         if (fname[i]) FreeMem(fname[i], fsiz);
       }
     }
     if (*text) {
       printf("%s\n",text);
     }
     if(IFFBase) {
       if (i = IffError()) {
         printf("IffError = %ld\n", i);
       }
           CloseLibrary(IFFBase);    /* MUST ALWAYS BE CLOSED !! */
         }
     if(IntuitionBase) CloseLibrary(IntuitionBase);
     if(GfxBase) CloseLibrary((struct Library *)GfxBase);
     exit(status);
 }
main (int argc, char * argv[])
Definition at line 63 of file show3.c.
References fname, fsiz, IntuitionBase, and screen.
 {
   long count,i;
   int dx, dy;
   WORD colortable[128];
   struct BitMapHeader *bmhd;
   if(!strcmp(argv[1],"?") || ((argc !=4) && (argc != 2))) {
     printf("Usage: %s redfile greenfile bluefile\n"
        "       %s filename (.[rgb] will be appended)\n",
        argv[0], argv[0]);
     exit(1);
   }
   if (argc == 4) {
     for (i=0; i<3; i++) {
       fname[i] = argv[i+1];
     }
   }else{
     fsiz = strlen(argv[1]) + 3;
     for (i=0; i<3; i++) {
       fname[i] = AllocMem(fsiz, 0L);
       if (!fname[i]) {
         Fail("Can't allocate memory", 1);
       }
       strcpy(fname[i], argv[1]);
       strcat(fname[i], ((i == 0) ? ".r" : ((i == 1) ? ".g" : ".b")));
     }
   }
   GfxBase = (struct GfxBase *)OpenLibrary("graphics.library",0L);
   if (!GfxBase) {
     Fail("Can't open graphics.library", 1);
   }
   IntuitionBase = OpenLibrary("intuition.library",0L);
   if (!IntuitionBase) {
     Fail("Can't open intuition.library", 1);
   }
   if(!(IFFBase = OpenLibrary(IFFNAME,IFFVERSION))) {
     Fail("Copy the iff.library to your LIBS: directory!", 1);
   }
   for (i=0; i<3; i++) {
     if(!(ifffile=OpenIFF(fname[i]))){
       Fail("Error opening file", 1);
     }
     if(!(bmhd=GetBMHD(ifffile))) {
       Fail("BitMapHeader not found", 1);
     }
     ns.Width      = bmhd->w;
     ns.Height     = bmhd->h;
     ns.Depth      = bmhd->nPlanes;
     ns.ViewModes  = GetViewModes(ifffile);
     if(!(screen[i] = OpenScreen(&ns))) {
       Fail("Can't open screen!", 1);
     }
     CenterScreen(screen[i], &dx, &dy);
     count = GetColorTab(ifffile,colortable);
     if(count>32L) count = 32L; /* Some HAM pictures have 64 colors ?! */
     LoadRGB4(&(screen[i]->ViewPort),colortable,count);
     if(!DecodePic(ifffile,&screen[i]->BitMap)) {
       Fail("Can't decode picture", 1);
     }
     CloseIFF(ifffile);
     ifffile = NULL;
   }
   SetTaskPri(FindTask(0L), 20L);    /* Run at high priority to reduce */
   for(;;) {             /* flicker! */
     if(!((*((UBYTE*)0xbfe001))&64)) break;  /* I know it's a hack */
     ScreenToFront(screen[0]);
     if(!((*((UBYTE*)0xbfe001))&64)) break;  /* I know it's a hack */
     ScreenToFront(screen[1]);
     if(!((*((UBYTE*)0xbfe001))&64)) break;  /* I know it's a hack */
     ScreenToFront(screen[2]);
   }
   Fail("", 0); /* Close the whole stuff */
 }
struct Library * OpenLibrary ()
struct Screen * OpenScreen ()
Variable Documentation
char* fname[3] = { ((void *)0) , ((void *)0) , ((void *)0) }
Definition at line 31 of file show3.c.
int fsiz = 0
Definition at line 32 of file show3.c.
Referenced by Fail(), and main().
struct GfxBase* GfxBase = ((void *)0)
Definition at line 21 of file show3.c.
struct Library * IFFBase = ((void *)0)
Definition at line 20 of file show3.c.
Referenced by Fail(), main(), and save().
APTR ifffile = ((void *)0)
Definition at line 30 of file show3.c.
struct Library* IntuitionBase = ((void *)0)
Definition at line 20 of file show3.c.
Referenced by Fail(), and main().
struct NewScreen ns
Initial value:
=
{
  0,0,0,0,0,0,0,  ((void *)0) , CUSTOMSCREEN | SCREENQUIET,  ((void *)0) , (STRPTR)"Show3",  ((void *)0) ,
   ((void *)0)
}
Definition at line 23 of file show3.c.
struct Screen* screen[3] = { ((void *)0) , ((void *)0) , ((void *)0) }
Definition at line 29 of file show3.c.